language: minimal
dist: xenial
services:
  - docker

stages:
  - Formatting
  - Compile
  - Test
  - Deploy

env:
  - SERVICE=service-1
  - SERVICE=service-2
  - SERVICE=service-3

script: make test-${SERVICE}

jobs:
  include:
    - stage: Formatting
      script: make ci-format
    - stage: Compile
      script: make
    - stage: Deploy
      script: make deploy
      if: branch = master
